// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZgsVEdTW6Quyi2ie1qeBWqzUjKJfG9y8',
    appId: '1:817415815905:web:f3b7cc038afb7e526aeda0',
    messagingSenderId: '817415815905',
    projectId: 'inklink-f0308',
    authDomain: 'inklink-f0308.firebaseapp.com',
    storageBucket: 'inklink-f0308.firebasestorage.app',
    measurementId: 'G-2WQHX0NDB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSWCykYBqX_WhuAMmg2O0luU_UtaEPcdU',
    appId: '1:817415815905:android:c0e8c32f4a6b05fd6aeda0',
    messagingSenderId: '817415815905',
    projectId: 'inklink-f0308',
    storageBucket: 'inklink-f0308.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFZNEzBv3-HXV1vGjXAaP63NGf8Qd9Irk',
    appId: '1:817415815905:ios:1cbc982d356998096aeda0',
    messagingSenderId: '817415815905',
    projectId: 'inklink-f0308',
    storageBucket: 'inklink-f0308.firebasestorage.app',
    iosBundleId: 'com.example.inklink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFZNEzBv3-HXV1vGjXAaP63NGf8Qd9Irk',
    appId: '1:817415815905:ios:1cbc982d356998096aeda0',
    messagingSenderId: '817415815905',
    projectId: 'inklink-f0308',
    storageBucket: 'inklink-f0308.firebasestorage.app',
    iosBundleId: 'com.example.inklink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZgsVEdTW6Quyi2ie1qeBWqzUjKJfG9y8',
    appId: '1:817415815905:web:48f20ca96f033f906aeda0',
    messagingSenderId: '817415815905',
    projectId: 'inklink-f0308',
    authDomain: 'inklink-f0308.firebaseapp.com',
    storageBucket: 'inklink-f0308.firebasestorage.app',
    measurementId: 'G-2FMXDQVV88',
  );
}
