// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WEB_FIREBASE_KEY']!,
    appId: '1:817415815905:web:f3b7cc038afb7e526aeda0',
    messagingSenderId: '817415815905',
    projectId: 'inklink-f0308',
    databaseURL: dotenv.env['FIREBASE_RTDB_URL']!,
    authDomain: 'inklink-f0308.firebaseapp.com',
    storageBucket: 'inklink-f0308.firebasestorage.app',
    measurementId: 'G-2WQHX0NDB3',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDROID_FIREBASE_KEY']!,
    appId: '1:817415815905:android:c0e8c32f4a6b05fd6aeda0',
    messagingSenderId: '817415815905',
    projectId: 'inklink-f0308',
    databaseURL: dotenv.env['FIREBASE_RTDB_URL']!,
    storageBucket: 'inklink-f0308.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOS_FIREBASE_KEY']!,
    appId: '1:817415815905:ios:1cbc982d356998096aeda0',
    messagingSenderId: '817415815905',
    projectId: 'inklink-f0308',
    databaseURL: dotenv.env['FIREBASE_RTDB_URL']!,
    storageBucket: 'inklink-f0308.firebasestorage.app',
    androidClientId:
        '817415815905-43taaregaicfjjfl84t8c42ckrk392qs.apps.googleusercontent.com',
    iosClientId:
        '817415815905-hm0ojvasv4ocgccfshj2508lmuthneng.apps.googleusercontent.com',
    iosBundleId: 'com.example.inklink',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['MACOS_FIREBASE_KEY']!,
    appId: '1:817415815905:ios:1cbc982d356998096aeda0',
    messagingSenderId: '817415815905',
    projectId: 'inklink-f0308',
    databaseURL: dotenv.env['FIREBASE_RTDB_URL']!,
    storageBucket: 'inklink-f0308.firebasestorage.app',
    androidClientId:
        '817415815905-43taaregaicfjjfl84t8c42ckrk392qs.apps.googleusercontent.com',
    iosClientId:
        '817415815905-hm0ojvasv4ocgccfshj2508lmuthneng.apps.googleusercontent.com',
    iosBundleId: 'com.example.inklink',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['WINDOWS_FIREBASE_KEY']!,
    appId: '1:817415815905:web:48f20ca96f033f906aeda0',
    messagingSenderId: '817415815905',
    projectId: 'inklink-f0308',
    databaseURL: dotenv.env['FIREBASE_RTDB_URL']!,
    authDomain: 'inklink-f0308.firebaseapp.com',
    storageBucket: 'inklink-f0308.firebasestorage.app',
    measurementId: 'G-2FMXDQVV88',
  );
}
